name: Build and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout commit
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Compile Binary
        run: make compile

      - name: Setup Dependencies
        run: make setup

      - name: Create Mocks
        run: make mocks

      - name: Run tests
        run: go test -v ./...
