name: Build Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64]
    steps:
      - name: Check commit
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build project
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: go build -o optimize-${{ matrix.os }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: optimize-${{ matrix.os }}
          draft: false
          prerelease: false
